spring:
  datasource:
    username: Guillaume
    password: WebESIEA0!
    url: jdbc:mysql://localhost:3306/ProjectWeb
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect